CREATE TABLE IF NOT EXISTS nobel_win(
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO nobel_win(
    YEAR,
    SUBJECT,
    WINNER,
    COUNTRY,
    CATEGORY
)
VALUES(
    1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
    (1970, 'PHYSICS', 'LOUIS NEAL', 'FRANCE', 'SCIENTIST'),
    (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
    (1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
    (1972, 'LITERATURE', 'BERNARD KALSON', 'GERMANY', 'ECONOMIST'),
    (1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
    (1973, 'BIOLOGY', 'PHILLIP', 'USA', 'PRIME MINISTER'),
    (1980, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
    (1975, 'PHYSICS', 'PETER', 'CHILIE', 'SCIENTIST');

SELECT * FROM nobel_win WHERE SUBJECT NOT LIKE 'P%';